### ISSUE TITLE
Not conneted

### ISSUE THREAD

**Issue by Tom60chat** [tylerbrawl/Galaxy-Plugin-Rockstar#105] opened 2020-04-08 19:30 UTC
I connect, the window closes and GOG say "Not connected __**Retry**__"

I restart GOG, delete C:\ProgramData\GOG.com\Galaxy\webcache\common and I still have the same problem.

My log file:
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/4452436/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)

**Comment by tylerbrawl** [comment] 2020-04-08 19:58
I'm closing this because it is a duplicate of #104.

**Closed by tylerbrawl** 2020-04-08 19:58 UTC
