### ISSUE TITLE
Lost 4 of 8 listed games

### ISSUE THREAD

**Issue by hightower5** [tylerbrawl/Galaxy-Plugin-Rockstar#126] opened 2020-12-02 16:42 UTC
Hello,

the plugin does only list a part of my games since yesterday.

Best regards

Hightower

**Comment by tylerbrawl** [comment] 2020-12-09 14:34
Are you still having this issue? If so, could you post your log file?

**Comment by hightower5** [comment] 2020-12-09 17:11
Yes, nothing changes.

[plugin-rockstar.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/5667497/plugin-rockstar.log)

**Comment by tylerbrawl** [comment] 2020-12-10 01:18
Now that I have updated my Rockstar Launcher and re-connected with the plugin, I am getting the same issue. I will get to work on this soon.

**Comment by tylerbrawl** [comment] 2020-12-10 02:28
Okay, I think I know what the issue is. Did this problem start occurring around the time when Rockstar released Red Dead Online as a standalone game? They added a bunch of redundant variants of Red Dead Redemption 2 to their internal games list, and the plugin would keep crashing when attempting to parse these.

The commit 04dd3eab6ffc891937b82b3e19ade5a06d70bb9f should fix the issue, but you will have to wait for the update to be pushed to Galaxy 2.0. If you want, however, you can manually install the updated version using the included .zip file. Let me know if the fix works so that I can close this issue. (Also, sorry for taking so long to get started on fixing this...)

[Plugin.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/5669898/Plugin.zip)

**Comment by hightower5** [comment] 2020-12-10 10:10
@tylerbrawl Indeed, the new update has fixed the problem. 

Thank you very much.

**Comment by tylerbrawl** [comment] 2020-12-10 14:01
That's great to hear. I will go ahead and close this issue. Thank you for your timely response.

**Closed by tylerbrawl** 2020-12-10 14:01 UTC
