### ISSUE TITLE
Refreshing authentication, research share

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [tylerbrawl/Galaxy-Plugin-Rockstar#9] opened 2019-10-15 10:26 UTC
Hey, 

i would like to share with you my research regarding possible refreshing of credentials, i couldn't progress with it any further but it might be of help to you.

Regarding the fingerprint i've had yet to decipher which information in it is required so there is probably a lot of unnecessary stuff passed there.

I don't remember most of the specifics right now of why i've did something like this and not differently but i will come back to you in case i remember/research anything else.

```python
@dataclass
class Token(object):
    _token: str = None
    _expires: float = None

    def set_token(self, token, expiration_time):
        self._token, self._expires = token, expiration_time

    def get_token(self):
        return self._token

    @property
    def expired(self):
        return self._expires <= time()
```

```python
import logging as log
import aiohttp
import asyncio
from base64 import b64encode
from galaxy.http import create_client_session
from yarl import URL
from time import time

from galaxy.api.errors import (
    InvalidCredentials, AuthenticationRequired
)
from definitions import Token
import pickle

class CookieJar(aiohttp.CookieJar):
    def __init__(self):
        super().__init__()
        self._cookies_updated_callback = None

    def set_cookies_updated_callback(self, callback):
        self._cookies_updated_callback = callback

    def update_cookies(self, cookies, url=URL()):
        super().update_cookies(cookies, url)
        if cookies and self._cookies_updated_callback:
            self._cookies_updated_callback(list(self))


class AuthenticatedHttpClient:

    def __init__(self, store_credentials_callback):
        self._refresh_token = Token()
        self._access_token = Token()
        self._store_credentials = store_credentials_callback
        self._cookie_jar = CookieJar()
        self._session = create_client_session(cookie_jar=self._cookie_jar)
        self.user = None

    def set_cookies_updated_callback(self, callback):
        self._cookie_jar.set_cookies_updated_callback(callback)

    def update_cookies(self, cookies):
        self._cookie_jar.update_cookies(cookies)

    def set_auth_lost_callback(self, callback):
        self._auth_lost_callback = callback

    async def request(self, method, url, **kwargs):
        try:
            try:
                return await self._session.request(method, url, **kwargs)
            except Exception as e:
                log.warning(f"Exception while performing request {method} {url} {repr(e)}")
                await self.refresh_authentication()
                return await self._session.request(method, url, **kwargs)
        except (AuthenticationRequired, InvalidCredentials) as e:
            log.error(f"Failed to refresh credentials, calling auth lost {repr(e)}")
            self._auth_lost_callback()
        except Exception as e:
            log.warning(f"Encountered exception while performing refresh workflow {repr(e)}")

    def load_stored_credentials(self, stored_credentials):
        stored_cookies = pickle.loads((bytes.fromhex(stored_credentials['cookies'])))
        stored_access_token = pickle.loads((bytes.fromhex(stored_credentials['access_token'])))
        stored_refresh_token = pickle.loads((bytes.fromhex(stored_credentials['refresh_token'])))

        cookies = {}
        for cookie in stored_cookies:
            cookies[cookie.key] = cookie.value

        self.update_cookies(cookies)
        self._access_token = stored_access_token
        self._refresh_token = stored_refresh_token

    async def refresh_authentication(self):
        try:
            await self._refresh_user()
            self._store_user_credentials()
        except InvalidCredentials:
            await self._refresh_credentials()
            await self._refresh_user()
            self._store_user_credentials()

    def _store_user_credentials(self):
        cookiez = [cookie for cookie in self._cookie_jar]
        access_token = self._access_token
        refresh_token = self._refresh_token

        self._store_credentials({'cookies': pickle.dumps(cookiez).hex(),
                                'access_token': pickle.dumps(access_token).hex(),
                                'refresh_token': pickle.dumps(refresh_token).hex()})

    def _get_cookies_for_headers(self):
        cookiez = ""
        for cookie in self._session.cookie_jar:
            cookiez += " " + cookie.key + "=" + cookie.value + ";"
        return cookiez

    async def _refresh_credentials(self):
        # Subject to change, investigating refresh atm
        log.info("REFRESHING CREDENTIALS")
        try:
            headers = {
            'X-Requested-With': 'XMLHttpRequest',
            'Cookie': self._get_cookies_for_headers(),
            'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8'
            }
            data = {'fingerprint':
                        {"fp": {"user_agent": "2bb0e97ded69e644dfe910aa29092060", "language": "en-US", "pixel_ratio": 1,
                                "timezone_offset": -120, "session_storage": 1, "local_storage": 1, "indexed_db": 1,
                                "open_database": 1, "cpu_class": "unknown", "navigator_platform": "Win32",
                                "do_not_track": "unknown", "regular_plugins": "9ea040ea929b41650b6826f99b9bf8d4",
                                "canvas": "de4b65eec2c8e0fe54d4781aa9ba0e90",
                                "webgl": "af296f908947021e75f9a244b57eda0c", "adblock": False, "has_lied_os": False,
                                "touch_support": "0;false;false", "device_name": "UC Browser on Windows",
                                "js_fonts": "561f5db5b62c7859e8bc4fa43e1e04cd"}}
                    }
            response = await self._session.request('POST', 'https://signin.rockstargames.com/connect/cors/check/rsg', headers=headers, json=data)

            log.info(response)
            log.info(await response.text())
            # remember me tokens in rockstar have expiry of 20 years
            self._refresh_token.set_token(await response.text(), time() + 60 * 60 * 24 * 365 * 20)

            log.info(self._refresh_token.expired)


            headers = {
                "content-type": "application/json",
                'cookie': self._get_cookies_for_headers(),
            }
            data = {"code": f"\"{self._refresh_token.get_token()}\""}
            log.info(data)
            response = await self._session.request('POST', 'https://www.rockstargames.com/auth/login.json', json=data, headers=headers)
        except Exception as e:
            log.info(repr(e))

        log.info(response)
        log.info(await response.text())
        log.info("FINISHED REFRESHING CREDENTIALS")

    async def _refresh_user(self):
        log.info("Refreshing User")

        headers = {
            "cookie": self._get_cookies_for_headers(),
            "authority": "www.rockstargames.com",
            "referer": "https://www.rockstargames.com/",
        }

        response = await self._session.request('GET', "https://www.rockstargames.com/auth/get-user.json", headers=headers)
        response = await response.json()

        if not response['loggedIn']:
            log.error(f'loggedIn: {response["loggedIn"]}')
            raise InvalidCredentials()

        access_token = response['user']['auth_token']['access_token']
        expires = (response['user']['auth_token']['expires_in'] * 60) + time()
        self._access_token.set_token(access_token, expires)

        refresh_token= response['user']['auth_token']['refresh_token']
        expires = (response['user']['auth_token']['refresh_expires_in'] * 60) + time()
        self._refresh_token.set_token(refresh_token, expires)
        self.user = response['user']
```

Hope this is of any help

**Comment by tylerbrawl** [comment] 2019-10-16 01:46
Thank you for this write-up. As you mentioned, the main issue here is finding out what, if any, parts of the fingerprint can be "faked." I will see what I can do as time goes on, but I expect this to take some time to figure out.

**Comment by tylerbrawl** [comment] 2019-10-16 07:31
It appears as though the Rockstar website is using the JavaScript module fingerprintjs2 for browser fingerprinting. Since the Python Requests module does not support JavaScript, we would have to try making a default fingerprint. If that does not work, then we would have to fall back to other options (such as Selenium).

**Comment by tylerbrawl** [comment] 2019-10-16 16:37
I found out some more information regarding fingerprint generation. The encrypted values within the fingerprint (user_agent, regular_plugins, canvas, webgl, and js_fonts) are found by returning their corresponding x64 128-bit MurmurHash3 value using the optional seed of 31. I will see what more I can find later on.

**Comment by tylerbrawl** [comment] 2019-10-18 00:04
I believe the remember me (or refresh) token is bound in some way to the generated fingerprint, so it seems like faking the fingerprint is not an option. Instead, I am going to use the JavaScript functionality of NextStep to replicate as best as possible the fingerprint generation that Rockstar uses.

**Comment by tylerbrawl** [comment] 2019-10-18 05:18
Great news, everybody: I found out how to replicate the generation of the fingerprint. It worked fine on my system, but it would be appreciated if others could test it, as well. I will include a .zip file containing the needed test files, if you have a Windows computer and would like to try it for yourself. Here are the steps for proper testing:

1. Extract the contents of fingerprint-test.zip (located at the bottom of this comment) into one single folder.
2. Open JS-Test.html **with Google Chrome** and take note of the fingerprint information that appears shortly after opening it.
3. With the Google Chrome developer tools open, visit https://www.rockstargames.com and inspect the network traffic at https://signin.rockstargames.com/connect/cors/check/rsg. Specifically, check the Request Payload information that is sent during the POST request to this endpoint.
4. Verify that the fingerprint that appears within the Request Payload matches that generated by JS-Test.html.

The reason that this needs to be done on Google Chrome with a Windows PC is because I explicitly set the device_name key to be "Chrome on Windows." (This is acceptable, since Galaxy 2.0 uses a version of Google Chrome during its NextStep call, and because the Rockstar Games Launcher is only available on Windows. If the launcher ever releases on Mac, or if the demand for a Social Club-only integration is high enough, then I can change the plugin.)


[**fingerprint-test.zip**](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3742389/fingerprint-test.zip)

**Comment by FriendsOfGalaxy** [comment] 2019-10-18 09:53
yup, they are the same, except on testjs there is no "device_name":"Chrome on Windows".
Good job!

**Comment by tylerbrawl** [comment] 2019-10-18 14:43
That's great to hear. I will begin integrating the JavaScript into the plugin.

**Comment by tylerbrawl** [comment] 2019-10-22 02:53
I believe that I have finally fixed re-authentication. If it is working correctly, then the user should remain authenticated for 20 years, but I would request some additional testing before releasing it fully. I have attached the latest binaries below. If the re-authentication works correctly for you, then I will send out this build as the final release of v0.2.
[plugin.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3753659/plugin.zip)

**Comment by tylerbrawl** [comment] 2019-10-22 19:53
I have just confirmed for myself that the user is indeed successfully re-authenticated after the 10-hour access token expires. As such, I will go ahead and close this issue and release v0.2 to the public as a final release. Thanks again for all of your help!

**Comment by FriendsOfGalaxy** [comment] 2019-10-24 14:13
I've played for some time with 0.2 version and unfortunately it's still loosing it's credentials. This time takes longer -> ~24h or so. Attached logs:
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3767978/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.zip)

**Comment by tylerbrawl** [comment] 2019-10-24 21:20
That's strange. I'll be sure to take a look at that.

**Comment by tylerbrawl** [comment] 2019-10-24 22:01
Are you using two-factor authentication? Logging in without it, it seems that the RMT is only needed for people using it (as the value is blank for users not using two-factor authentication), while the rsso cookie is needed for every account.

**Comment by tylerbrawl** [comment] 2019-10-24 22:49
Assuming that the issue was because of two-factor authentication being disabled, I have created a fix for that. The below build incorporates the proposed fix. If you still have errors with this build, then please let me know.
[plugin-auth-test.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3769731/plugin-auth-test.zip)

**Comment by christofin** [comment] 2019-10-29 16:07
What I have noticed with this issue is that my credentials appear to be stored in GOG 2.0, but as soon as I log in to the Rockstar Social Club website, my session in GOG 2.0 is expired and I have to re-scan my library for any additional games. 

I don't have two factor enabled on my Rockstar account yet. Let me know how I can help test this issue (I can hold off on enabling two factor if you want me to try to run that zip file).

**Comment by tylerbrawl** [comment] 2019-10-29 22:23
Did you download the new v0.2.1 release? Either download that or the plugin-auth-test.zip file above (although I suggest that you instead download the v0.2.1 release from [here](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/releases/tag/v0.2.1)).

**Comment by christofin** [comment] 2019-10-30 02:51
I downloaded that after I saw your comment and it fixed the issue, thanks. It still seems to not be tracking any of my playtime whereas when I manually added the .exe before using the plugin, it did, but I can make a separate issue for that.

**Comment by tylerbrawl** [comment] 2019-10-30 06:13
Yes, that should be on a separate issue. Still, I appreciate your testing regarding the re-authentication. Since you confirm that the issue is fixed, I will close this issue once more.

**Closed by tylerbrawl** 2019-10-30 06:13 UTC
