### ISSUE TITLE
Stopped working after Red Dead Online Update on 28th

### ISSUE THREAD

**Issue by FaithTheSlayer** [tylerbrawl/Galaxy-Plugin-Rockstar#115] opened 2020-07-30 13:38 UTC
Please fix!

**Comment by Euxiniar** [comment] 2020-07-30 16:01
I can confirm that I can't connect anymore

**Comment by felipeocr** [comment] 2020-07-30 20:50
Same error here.

**Comment by ElAlderson** [comment] 2020-08-02 10:28
This is the same issue as #114 . Having the same problem.

**Comment by FaithTheSlayer** [comment] 2020-08-02 12:30
Isn't anyone going to fix it?

**Comment by ElAlderson** [comment] 2020-08-02 14:23
I think people are trying their best for now. For us, the best we can do is raise a flag and then wait.

**Comment by tylerbrawl** [comment] 2020-08-03 18:47
I'm closing this because it appears to be a duplicate of #114. Please discuss the issue further there.

**Closed by tylerbrawl** 2020-08-03 18:47 UTC
Labels: duplicate
