### ISSUE TITLE
Plugin states "offline", login loop!

### ISSUE THREAD

**Issue by chrissix666** [tylerbrawl/Galaxy-Plugin-Rockstar#116] opened 2020-07-31 23:45 UTC
Since a few days the plugin in stating always "offline" and no sucess on login on whatever login method (there are several available for Rockstar Games Social club)
Does somebody have the same issue?

**Comment by b1oki** [comment] 2020-08-01 09:56
Looks like #114

**Comment by tylerbrawl** [comment] 2020-08-03 18:48
I'm closing this because it appears to be a duplicate of #114. Please discuss the issue further there.

**Closed by tylerbrawl** 2020-08-03 18:48 UTC
Labels: duplicate
